FROM python:3.10-slim

LABEL maintainer="MLOps Lab1"
LABEL description="Wine classification using GradientBoosting"

WORKDIR /app

COPY src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ .

CMD ["python", "main.py"]
